### ISSUE TITLE
Add basic flair functionality

### ISSUE THREAD

**Issue by Brottweiler** [Electroid/PGM#53]
https://github.com/Electroid/PGM/issues/5 does mention that "flairs are now out-of-scope for PGM", which sounds like flairs should not be included in PGM. I think flairs needs to be in PGM since if you try to use flairs (also known as prefixes) in any other way, it replaces the entire chat formatting.

Something like a configuration where you can make new flairs and assign permissions for them;

```yml
flair:
  admin:
    symbol: ❖
    color: gold
  mod:
    symbol: ❖
    color: red
```
Then a player who gets the permission `pgm.flair.admin` gets the gold symbol and `pgm.flair.mod` gets the red one.
